config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  mount_uploader :avatar, AvatarUploader

  after_save :crop_avatar

  validates :password, length: { in: 6..20 }

  private

  def crop_avatar
    Cropper.perform_at(30.seconds, id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :require_login, only: :show
  before_action :set_user, only: %i[show update edit]

  def index; end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :avatar, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Infobot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar'%>
    <div class="container">
      <%= yield %>
    </div>

    <%= render 'shared/footer'%>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="fixed-bottom"> 
    &copy; Malinin Mikhail<br>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <h1>
    <%= link_to "INFOBOT TEST APPLICATION", root_path, class: 'navbar-brand' %>
  </h1>

    <span class="navbar-text">
      <% if signed_in? %>
      Welcome, <b><%= current_user.email %></b> |
        <%= link_to t('.logout'), sign_out_path, method: :delete %>
        <%= link_to t('.profile'), user_path(current_user), method: :get %>
      <% else %>
        <%=link_to t('.login'), sign_in_path %> |
        <%=link_to t('.sign_up'), sign_up_path %>
      <% end %>
    </span>
</nav>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.password_field :password %>
</div>

<div>
  <%= form.file_field :avatar %>
</div>

app/views/users/edit.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= bootstrap_form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>
    <div class="submit-field">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= bootstrap_form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= @user.email %>
<br>
<%= link_to t('.Edit profile'), edit_user_path(@user) %>
<br>
<%= image_tag(@user.avatar.url, alt: 'avatar') if @user.avatar? %>